version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - appnet

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: veterinaria_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vete2025
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
